image: node:14.17
clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
           caches:
             - node
           script:
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
